# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'allnetsdialog.ui'
#
# Created: Wed Mar 18 01:55:38 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_allNetsDialog(object):
    def setupUi(self, allNetsDialog):
        allNetsDialog.setObjectName(_fromUtf8("allNetsDialog"))
        allNetsDialog.resize(431, 467)
        self.buttonBox = QtGui.QDialogButtonBox(allNetsDialog)
        self.buttonBox.setGeometry(QtCore.QRect(70, 430, 341, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Horizontal)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.treeWidget = QtGui.QTreeWidget(allNetsDialog)
        self.treeWidget.setGeometry(QtCore.QRect(10, 10, 411, 371))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.treeWidget.setFont(font)
        self.treeWidget.setObjectName(_fromUtf8("treeWidget"))
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(0, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0.setCheckState(1, QtCore.Qt.Unchecked)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        item_0 = QtGui.QTreeWidgetItem(self.treeWidget)
        self.treeWidget.header().setDefaultSectionSize(130)
        self.checkBox_4 = QtGui.QCheckBox(allNetsDialog)
        self.checkBox_4.setGeometry(QtCore.QRect(190, 410, 141, 17))
        self.checkBox_4.setObjectName(_fromUtf8("checkBox_4"))
        self.checkBox = QtGui.QCheckBox(allNetsDialog)
        self.checkBox.setGeometry(QtCore.QRect(10, 390, 151, 17))
        self.checkBox.setObjectName(_fromUtf8("checkBox"))
        self.checkBox_3 = QtGui.QCheckBox(allNetsDialog)
        self.checkBox_3.setGeometry(QtCore.QRect(10, 410, 131, 17))
        self.checkBox_3.setObjectName(_fromUtf8("checkBox_3"))
        self.checkBox_2 = QtGui.QCheckBox(allNetsDialog)
        self.checkBox_2.setGeometry(QtCore.QRect(190, 390, 141, 17))
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))

        self.retranslateUi(allNetsDialog)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), allNetsDialog.accept)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), allNetsDialog.reject)
        QtCore.QMetaObject.connectSlotsByName(allNetsDialog)

    def retranslateUi(self, allNetsDialog):
        allNetsDialog.setWindowTitle(_translate("allNetsDialog", "Dialog", None))
        self.treeWidget.headerItem().setText(0, _translate("allNetsDialog", "Все сети", None))
        self.treeWidget.headerItem().setText(1, _translate("allNetsDialog", "2УРОВЕНЬ", None))
        __sortingEnabled = self.treeWidget.isSortingEnabled()
        self.treeWidget.setSortingEnabled(False)
        self.treeWidget.topLevelItem(0).setText(0, _translate("allNetsDialog", "Здания", None))
        self.treeWidget.topLevelItem(1).setText(0, _translate("allNetsDialog", "Картинки", None))
        self.treeWidget.topLevelItem(2).setText(0, _translate("allNetsDialog", "Водопровод", None))
        self.treeWidget.topLevelItem(3).setText(0, _translate("allNetsDialog", "----Узлы", None))
        self.treeWidget.topLevelItem(4).setText(1, _translate("allNetsDialog", "Колодец", None))
        self.treeWidget.topLevelItem(5).setText(1, _translate("allNetsDialog", "Изгиб", None))
        self.treeWidget.topLevelItem(6).setText(1, _translate("allNetsDialog", "Ввод", None))
        self.treeWidget.topLevelItem(7).setText(1, _translate("allNetsDialog", "Врезка", None))
        self.treeWidget.topLevelItem(8).setText(1, _translate("allNetsDialog", "Вход нас. станции", None))
        self.treeWidget.topLevelItem(9).setText(1, _translate("allNetsDialog", "Выход нас. станции", None))
        self.treeWidget.topLevelItem(10).setText(1, _translate("allNetsDialog", "Вход резервуара", None))
        self.treeWidget.topLevelItem(11).setText(1, _translate("allNetsDialog", "Выход резервуара", None))
        self.treeWidget.topLevelItem(12).setText(1, _translate("allNetsDialog", "Камера", None))
        self.treeWidget.topLevelItem(13).setText(1, _translate("allNetsDialog", "Источник", None))
        self.treeWidget.topLevelItem(14).setText(1, _translate("allNetsDialog", "Водомер", None))
        self.treeWidget.topLevelItem(15).setText(1, _translate("allNetsDialog", "Насос", None))
        self.treeWidget.topLevelItem(16).setText(1, _translate("allNetsDialog", "Деталировка", None))
        self.treeWidget.topLevelItem(17).setText(0, _translate("allNetsDialog", "----Участки", None))
        self.treeWidget.topLevelItem(18).setText(1, _translate("allNetsDialog", "Сталь", None))
        self.treeWidget.topLevelItem(19).setText(1, _translate("allNetsDialog", "Чугун", None))
        self.treeWidget.topLevelItem(20).setText(1, _translate("allNetsDialog", "Железобетон", None))
        self.treeWidget.topLevelItem(21).setText(1, _translate("allNetsDialog", "Асбестоцемент", None))
        self.treeWidget.topLevelItem(22).setText(1, _translate("allNetsDialog", "Пластмасса", None))
        self.treeWidget.topLevelItem(23).setText(1, _translate("allNetsDialog", "Керамика", None))
        self.treeWidget.topLevelItem(24).setText(1, _translate("allNetsDialog", "Неизвестен", None))
        self.treeWidget.topLevelItem(25).setText(1, _translate("allNetsDialog", "Стеклопластик", None))
        self.treeWidget.topLevelItem(26).setText(0, _translate("allNetsDialog", "Канализация", None))
        self.treeWidget.topLevelItem(27).setText(0, _translate("allNetsDialog", "----Узлы", None))
        self.treeWidget.topLevelItem(28).setText(1, _translate("allNetsDialog", "Колодец", None))
        self.treeWidget.topLevelItem(29).setText(1, _translate("allNetsDialog", "Изгиб", None))
        self.treeWidget.topLevelItem(30).setText(1, _translate("allNetsDialog", "Выпуск", None))
        self.treeWidget.topLevelItem(31).setText(1, _translate("allNetsDialog", "Врезка", None))
        self.treeWidget.topLevelItem(32).setText(1, _translate("allNetsDialog", "Вход нас. станции", None))
        self.treeWidget.topLevelItem(33).setText(1, _translate("allNetsDialog", "Выход нас. станции", None))
        self.treeWidget.topLevelItem(34).setText(1, _translate("allNetsDialog", "Дождеприемник", None))
        self.treeWidget.topLevelItem(35).setText(1, _translate("allNetsDialog", "Камера", None))
        self.treeWidget.topLevelItem(36).setText(0, _translate("allNetsDialog", "----Участки", None))
        self.treeWidget.topLevelItem(37).setText(1, _translate("allNetsDialog", "Сталь", None))
        self.treeWidget.topLevelItem(38).setText(1, _translate("allNetsDialog", "Чугун", None))
        self.treeWidget.topLevelItem(39).setText(1, _translate("allNetsDialog", "Железобетон", None))
        self.treeWidget.topLevelItem(40).setText(1, _translate("allNetsDialog", "Асбестоцемент", None))
        self.treeWidget.topLevelItem(41).setText(1, _translate("allNetsDialog", "Пластмасса", None))
        self.treeWidget.topLevelItem(42).setText(1, _translate("allNetsDialog", "Керамика", None))
        self.treeWidget.topLevelItem(43).setText(1, _translate("allNetsDialog", "Неизвестен", None))
        self.treeWidget.topLevelItem(44).setText(1, _translate("allNetsDialog", "Стеклопластик", None))
        self.treeWidget.topLevelItem(45).setText(0, _translate("allNetsDialog", "Теплосеть", None))
        self.treeWidget.topLevelItem(46).setText(0, _translate("allNetsDialog", "Дренаж", None))
        self.treeWidget.topLevelItem(47).setText(0, _translate("allNetsDialog", "Контуры", None))
        self.treeWidget.topLevelItem(48).setText(0, _translate("allNetsDialog", "Ливневая канализ.", None))
        self.treeWidget.topLevelItem(49).setText(0, _translate("allNetsDialog", "Эл. защита(газ)", None))
        self.treeWidget.topLevelItem(50).setText(0, _translate("allNetsDialog", "Освещение", None))
        self.treeWidget.topLevelItem(51).setText(0, _translate("allNetsDialog", "Геодезия", None))
        self.treeWidget.topLevelItem(52).setText(0, _translate("allNetsDialog", "Улицы", None))
        self.treeWidget.topLevelItem(53).setText(0, _translate("allNetsDialog", "Телеф. канал.", None))
        self.treeWidget.topLevelItem(54).setText(0, _translate("allNetsDialog", "Эл. сеть 0.4", None))
        self.treeWidget.topLevelItem(55).setText(0, _translate("allNetsDialog", "Эл. сеть 6", None))
        self.treeWidget.topLevelItem(56).setText(0, _translate("allNetsDialog", "Эл. сеть 10", None))
        self.treeWidget.topLevelItem(57).setText(0, _translate("allNetsDialog", "Газ высокий", None))
        self.treeWidget.topLevelItem(58).setText(0, _translate("allNetsDialog", "Газ низкий", None))
        self.treeWidget.topLevelItem(59).setText(0, _translate("allNetsDialog", "Н/д водопр.", None))
        self.treeWidget.topLevelItem(60).setText(0, _translate("allNetsDialog", "Н/д канализ.", None))
        self.treeWidget.setSortingEnabled(__sortingEnabled)
        self.checkBox_4.setText(_translate("allNetsDialog", "Штриховать задания", None))
        self.checkBox.setText(_translate("allNetsDialog", "Большие диам. - тонкие", None))
        self.checkBox_3.setText(_translate("allNetsDialog", "Не рисовать узлы", None))
        self.checkBox_2.setText(_translate("allNetsDialog", "Рисовать внутри сети", None))

