# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'wataccolstyledockwidget.ui'
#
# Created: Tue Mar 17 23:19:09 2015
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_waOldStyleDockWidget(object):
    def setupUi(self, waOldStyleDockWidget):
        waOldStyleDockWidget.setObjectName(_fromUtf8("waOldStyleDockWidget"))
        waOldStyleDockWidget.resize(118, 495)
        self.dockWidgetContents = QtGui.QWidget()
        self.dockWidgetContents.setObjectName(_fromUtf8("dockWidgetContents"))
        self.pushButton = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton.setGeometry(QtCore.QRect(10, 0, 100, 23))
        self.pushButton.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.pushButton_2 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_2.setGeometry(QtCore.QRect(10, 20, 100, 23))
        self.pushButton_2.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_2.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_2.setObjectName(_fromUtf8("pushButton_2"))
        self.pushButton_3 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_3.setGeometry(QtCore.QRect(10, 40, 100, 23))
        self.pushButton_3.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_3.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.pushButton_4 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setGeometry(QtCore.QRect(10, 60, 100, 23))
        self.pushButton_4.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_4.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.pushButton_5 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_5.setGeometry(QtCore.QRect(10, 80, 100, 23))
        self.pushButton_5.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_5.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_5.setObjectName(_fromUtf8("pushButton_5"))
        self.pushButton_6 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_6.setGeometry(QtCore.QRect(10, 100, 100, 23))
        self.pushButton_6.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_6.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_6.setObjectName(_fromUtf8("pushButton_6"))
        self.pushButton_7 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_7.setGeometry(QtCore.QRect(10, 120, 100, 23))
        self.pushButton_7.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_7.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_7.setObjectName(_fromUtf8("pushButton_7"))
        self.pushButton_8 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_8.setGeometry(QtCore.QRect(10, 140, 100, 23))
        self.pushButton_8.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_8.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_8.setObjectName(_fromUtf8("pushButton_8"))
        self.pushButton_9 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_9.setGeometry(QtCore.QRect(10, 160, 100, 23))
        self.pushButton_9.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_9.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_9.setObjectName(_fromUtf8("pushButton_9"))
        self.pushButton_10 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_10.setGeometry(QtCore.QRect(10, 180, 100, 23))
        self.pushButton_10.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_10.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_10.setObjectName(_fromUtf8("pushButton_10"))
        self.pushButton_11 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_11.setEnabled(False)
        self.pushButton_11.setGeometry(QtCore.QRect(10, 200, 100, 23))
        self.pushButton_11.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_11.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_11.setObjectName(_fromUtf8("pushButton_11"))
        self.pushButton_12 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_12.setGeometry(QtCore.QRect(10, 220, 100, 23))
        self.pushButton_12.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_12.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_12.setObjectName(_fromUtf8("pushButton_12"))
        self.pushButton_13 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_13.setGeometry(QtCore.QRect(10, 240, 100, 23))
        self.pushButton_13.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_13.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_13.setObjectName(_fromUtf8("pushButton_13"))
        self.pushButton_14 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_14.setGeometry(QtCore.QRect(10, 260, 100, 23))
        self.pushButton_14.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_14.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_14.setObjectName(_fromUtf8("pushButton_14"))
        self.pushButton_15 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_15.setGeometry(QtCore.QRect(10, 280, 100, 23))
        self.pushButton_15.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_15.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_15.setObjectName(_fromUtf8("pushButton_15"))
        self.pushButton_16 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_16.setGeometry(QtCore.QRect(10, 300, 100, 23))
        self.pushButton_16.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_16.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_16.setObjectName(_fromUtf8("pushButton_16"))
        self.pushButton_17 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_17.setGeometry(QtCore.QRect(10, 320, 100, 23))
        self.pushButton_17.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_17.setBaseSize(QtCore.QSize(0, 0))
        self.pushButton_17.setObjectName(_fromUtf8("pushButton_17"))
        self.pushButton_18 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_18.setGeometry(QtCore.QRect(10, 340, 100, 23))
        self.pushButton_18.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_18.setObjectName(_fromUtf8("pushButton_18"))
        self.pushButton_19 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_19.setGeometry(QtCore.QRect(10, 360, 100, 23))
        self.pushButton_19.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_19.setObjectName(_fromUtf8("pushButton_19"))
        self.pushButton_20 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_20.setGeometry(QtCore.QRect(10, 380, 100, 23))
        self.pushButton_20.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_20.setObjectName(_fromUtf8("pushButton_20"))
        self.pushButton_21 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_21.setGeometry(QtCore.QRect(10, 400, 100, 23))
        self.pushButton_21.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_21.setObjectName(_fromUtf8("pushButton_21"))
        self.pushButton_22 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_22.setGeometry(QtCore.QRect(10, 420, 100, 23))
        self.pushButton_22.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_22.setObjectName(_fromUtf8("pushButton_22"))
        self.pushButton_23 = QtGui.QPushButton(self.dockWidgetContents)
        self.pushButton_23.setGeometry(QtCore.QRect(10, 440, 100, 23))
        self.pushButton_23.setMaximumSize(QtCore.QSize(100, 16777215))
        self.pushButton_23.setObjectName(_fromUtf8("pushButton_23"))
        waOldStyleDockWidget.setWidget(self.dockWidgetContents)

        self.retranslateUi(waOldStyleDockWidget)
        QtCore.QMetaObject.connectSlotsByName(waOldStyleDockWidget)

    def retranslateUi(self, waOldStyleDockWidget):
        waOldStyleDockWidget.setWindowTitle(_translate("waOldStyleDockWidget", "Действия (старомодн.)", None))
        self.pushButton.setText(_translate("waOldStyleDockWidget", "Крупно", None))
        self.pushButton_2.setText(_translate("waOldStyleDockWidget", "Мелко", None))
        self.pushButton_3.setText(_translate("waOldStyleDockWidget", "Запоминание", None))
        self.pushButton_4.setText(_translate("waOldStyleDockWidget", "Дигитайзер", None))
        self.pushButton_5.setText(_translate("waOldStyleDockWidget", "Лупа", None))
        self.pushButton_6.setText(_translate("waOldStyleDockWidget", "Выбор сети", None))
        self.pushButton_7.setText(_translate("waOldStyleDockWidget", "Все сети", None))
        self.pushButton_8.setText(_translate("waOldStyleDockWidget", "Копия", None))
        self.pushButton_9.setText(_translate("waOldStyleDockWidget", "Линейка", None))
        self.pushButton_10.setText(_translate("waOldStyleDockWidget", "Объект ?", None))
        self.pushButton_11.setText(_translate("waOldStyleDockWidget", "Планшет ?", None))
        self.pushButton_12.setText(_translate("waOldStyleDockWidget", "Адрес ?", None))
        self.pushButton_13.setText(_translate("waOldStyleDockWidget", "Разрез", None))
        self.pushButton_14.setText(_translate("waOldStyleDockWidget", "Профиль", None))
        self.pushButton_15.setText(_translate("waOldStyleDockWidget", "Перекресток ?", None))
        self.pushButton_16.setText(_translate("waOldStyleDockWidget", "Координаты ?", None))
        self.pushButton_17.setText(_translate("waOldStyleDockWidget", "Улицы", None))
        self.pushButton_18.setText(_translate("waOldStyleDockWidget", "Улицы/адреса", None))
        self.pushButton_19.setText(_translate("waOldStyleDockWidget", "Общий план", None))
        self.pushButton_20.setText(_translate("waOldStyleDockWidget", "Раскрасить", None))
        self.pushButton_21.setText(_translate("waOldStyleDockWidget", "Отметки", None))
        self.pushButton_22.setText(_translate("waOldStyleDockWidget", "Длины", None))
        self.pushButton_23.setText(_translate("waOldStyleDockWidget", "Уклоны", None))

